[package]
name = "rs-actor"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { "version" = "1.41", "features" = ["full"]}
uuid = { "version" = "1.11", "features" = ["v4", "fast-rng", "macro-diagnostics"]}
futures ={ "version" = "0.3"}
